name: Stainless — Upload OpenAPI specification
description: Upload your OpenAPI spec to update your Stainless SDKs (and, if configured, add example snippets to your API docs)
branding:
  icon: book-open
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  stainless_api_key:
    description: "Stainless API key."
    required: true
  input_path:
    description: "Path to the OpenAPI file."
    required: true
  config_path:
    description: "To to the Stainless config file."
    required: false
  output_path:
    description: "Output path for the decorated OpenAPI spec."
