name: upload-openapi-spec
description: |
  Upload your OpenAPI spec to trigger regeneration of your SDKs.

  Can also output a copy of your OpenAPI spec decorated with sample code
  for passing along to API documentation providers like ReadMe.
branding:
  icon: book-open
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  stainless_api_key:
    description: 'Stainless API key.'
    required: true
  input_path:
    description: 'Path to the OpenAPI file.'
    required: true
  output_path:
    description: 'Output path for the decorated OpenAPI spec.'
