name: decorate-spec
description: Generate "decorated" openapi spec for readme.com
branding:
  icon: book-open
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  token:
    description: GitHub token for cloning the repo
    required: true
